- alias: 编辑用户组信息
  uri: /api/v1/groups/{group_id}
  act: put
- alias: 添加用户组成员
  uri:  /api/v1/groups/{group_id}/users
  act: post
- alias: 获取某一用户组下的所有用户
  uri:  /api/v1/groups/{group_id}/users
  act: get
- alias: 编辑用户组的用户状态
  uri: /api/v1/groups/{group_id}/users
  act: put
- alias: 用户-团队角色绑定
  uri: /api/v1/user-role/group/{group_id}
  act: post
- alias: 用户-团队角色解绑
  uri: /api/v1/user-role/group/{group_id}
  act: delete
- alias: scope-团队角色绑定
  uri: /api/v1/scope-role/group/{group_id}
  act: post
- alias: scope-团队角色解绑
  uri: /api/v1/scope-role/group/{group_id}
  act: delete
- alias: 以团队名义接受需求
  uri: /api/v1/requirement/{requirement_id}/group/{group_id}/accept
  act: put
- alias: 以团队名义发布需求
  uri: /api/v1/requirement/group/{group_id}
  act: post