- uri: /api/v1/product/%d
  act: delete
  alias: 删除Product
  table: product
- uri: /api/v1/product/%d
  act: put
  alias: 修改Product
  table: product
- uri: /api/v2/milestone/%d
  act: put
  alias: 修改Milestone
  table: milestone
- uri: /api/v2/milestone/%d
  act: delete
  alias: 删除Milestone
  table: milestone
- uri: /api/v2/milestone/%d
  act: put
  alias: 修改Milestone
  table: milestone
- uri: /api/v1/pmachine/%d
  act: delete
  alias: 删除Pmachine
  table: pmachine
- uri: /api/v1/pmachine/%d
  act: put
  alias: 修改Pmachine
  table: pmachine
- uri: /api/v1/pmachine/%d/power
  act: put
  alias: 修改Pmachine上下电
  table: pmachine
- uri: /api/v1/pmachine/%d/install
  act: put
  alias: 安装Pmachine
  table: pmachine
- uri: /api/v1/pmachine/%d/delay
  act: put
  alias: 修改Pmachine占用时间
  table: pmachine
- uri: /api/v1/pmachine/%d/occupy
  act: put
  alias: 占用Pmachine
  table: pmachine
- uri: /api/v1/pmachine/%d/release
  act: put
  alias: 释放Pmachine
  table: pmachine
- uri: /api/v1/machine-group/%d
  act: delete
  alias: 删除Machine_Group
  table: machine_group
- uri: /api/v1/machine-group/%d
  act: put
  alias: 修改Machine_Group
  table: machine-group
- uri: /api/v1/vmachine/%d
  act: delete
  alias: 删除Vmachine
  table: vmachine
- uri: /api/v1/vmachine/%d
  act: put
  alias: 修改Vmachine
  table: vmachine
- uri: /api/v1/vmachine/%d/ipaddr
  act: put
  alias: 修改Vmachine的ip地址
  table: vmachine
- uri: /api/v1/template/%d
  act: delete
  alias: 删除Template
  table: template
- uri: /api/v1/template/%d
  act: put
  alias: 修改Template
  table: template
- uri: /api/v1/framework/%d
  act: delete
  alias: 删除Framework
  table: framework
- uri: /api/v1/framework/%d
  act: put
  alias: 修改Framework
  table: framework
- uri: /api/v1/git_repo/%d
  act: delete
  alias: 删除GitRepo
  table: git_repo
- uri: /api/v1/git_repo/%d
  act: put
  alias: 修改GitRepo
  table: git_repo