# 平台角色初始化配置

# 公共角色
public:
    # 管理员
    administrator: admin
    # 一般用户
    user:
        - visitor
        - member
    # 公共基础角色
    default: default

# 组织角色
org:
    # 管理员
    administrator: admin
    # 一般用户
    user:
        - member
    # 默认用户:用户加入组织时,绑定的最基础用户角色
    default: default

# 团队角色
group:
    # 管理员
    administrator: admin
    # 一般用户
    user:
        - member
    # 默认用户:用户加入用户组时,绑定的最基础用户角色
    default: default