openEuler-22.09-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.09_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.09_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.09_x86
  test_suite: repo_test,base_test,integrate_test,LTP_test_x86,install_virtual_img_testsuite,pxe_install_guimode_22.09_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-20.03-LTS-SP3-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_lts3_SP3_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_20.03_LTS_SP3_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_20.03_LTS_SP3_x86
  test_suite: repo_test,base_test,integrate_test,LTP_test_x86,install_virtual_img_testsuite,pxe_install_guimode_lts3_SP3_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-20.03-LTS-SP3-aarch64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_lts3_SP3
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_20.03_LTS_SP3
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_20.03_LTS_SP3
  test_suite: repo_test,base_test,integrate_test,LTP_test,install_virtual_img_testsuite,pxe_install_guimode_lts3_SP3,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-22.03-LTS-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.03_LTS_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.03_LTS_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.03_LTS_x86
  test_suite: repo_test,fundamental_test,base_test,integrate_test,LTP_test_x86,install_virtual_img_testsuite,pxe_install_guimode_22.03_LTS_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-22.03-LTS-aarch64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.03_LTS
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.03_LTS
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.03_LTS
  test_suite: repo_test,fundamental_test,base_test,integrate_test,LTP_test,install_virtual_img_testsuite,pxe_install_guimode_22.03_LTS,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-20.03-LTS-SP1-aarch64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_lts3_SP1
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_20.03_LTS_SP1
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_20.03_LTS_SP1
  test_suite: repo_test,base_test,integrate_test,LTP_test,install_virtual_img_testsuite,pxe_install_guimode_lts3_SP1,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-20.03-LTS-SP1-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_lts3_SP1_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_20.03_LTS_SP1_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_20.03_LTS_SP1_x86
  test_suite: repo_test,base_test,integrate_test,LTP_test_x86,install_virtual_img_testsuite,pxe_install_guimode_lts3_SP1_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-20.03-LTS-SP2-aarch64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_lts3_SP2
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_20.03_LTS_SP2
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_20.03_LTS_SP2
  test_suite: repo_test,base_test,integrate_test,LTP_test,install_virtual_img_testsuite,pxe_install_guimode_lts3_SP2,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-20.03-LTS-SP2-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_lts3_SP2_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_20.03_LTS_SP2_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_20.03_LTS_SP2_x86
  test_suite: repo_test,base_test,integrate_test,LTP_test_x86,install_virtual_img_testsuite,pxe_install_guimode_lts3_SP2_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-22.03-LTS-SP1-aarch64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.03_LTS_SP1
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.03_LTS_SP1
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.03_LTS_SP1
  test_suite: repo_test,fundamental_test,base_test,integrate_test,LTP_test,install_virtual_img_testsuite,pxe_install_guimode_22.03_LTS_SP1,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-22.03-LTS-SP1-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.03_LTS_SP1_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.03_LTS_SP1_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.03_LTS_SP1_x86
  test_suite: repo_test,fundamental_test,base_test,integrate_test,LTP_test_x86,install_virtual_img_testsuite,pxe_install_guimode_22.03_LTS_SP1_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-22.03-LTS-Next-aarch64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.03_Next
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.03_LTS_Next
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.03_LTS_Next
  test_suite: repo_test,base_test,integrate_test,LTP_test,pxe_install_guimode_22.03_Next,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test

openEuler-22.03-LTS-Next-x86_64-dvd:
  pxe_repo_path: /var/www/html/productrepo/openEuler_22.03_Next_x86
  pxe_tftpboot_path: /var/lib/tftpboot/openEuler_22.03_LTS_Next_x86
  pxe_efi_path: /var/lib/tftpboot/openEuler/GUI_22.03_LTS_Next_x86
  test_suite: repo_test,base_test,integrate_test,LTP_test_x86,pxe_install_guimode_22.03_Next_x86,docker_test,iSula_test,kdump_test,OVS_test,rpm_test_1,rpm_test_2,rpm_test_3,rpm_test_4,rpm_test_5,module_test


